module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    moduleNameMapper: {
        "^@root/(.*)": ["<rootDir>/$1"],
        "^@lib/(.*)": ["<rootDir>/lib/$1"],
        "^@lib": ["<rootDir>/lib/index"],
        "^@cli/(.*)": ["<rootDir>/lib/cli/$1"],
        "^@cli": ["<rootDir>/lib/cli/index"],
        "^@db/(.*)": ["<rootDir>/lib/db/$1"],
        "^@db": ["<rootDir>/lib/db/index"],
        "^@decorators/(.*)": ["<rootDir>/lib/decorators/$1"],
        "^@decorators": ["<rootDir>/lib/decorators/index"],
        "^@generators/(.*)": ["<rootDir>/lib/generators/$1"],
        "^@generators": ["<rootDir>/lib/generators/index"],
        "^@logger/(.*)": ["<rootDir>/lib/logger/$1"],
        "^@logger": ["<rootDir>/lib/logger/index"],
        "^@patches/(.*)": ["<rootDir>/lib/patches/$1"],
        "^@patches": ["<rootDir>/lib/patches/index"],
        "^@tools/(.*)": ["<rootDir>/lib/tools/$1"],
        "^@tools": ["<rootDir>/lib/tools/index"],
        "^@transformers/(.*)": ["<rootDir>/lib/transformers/$1"],
        "^@transformers": ["<rootDir>/lib/transformers/index"],
        "^@testing/(.*)": ["<rootDir>/lib/testing/$1"],
        "^@testing": ["<rootDir>/lib/testing/index"],
        "^@types/(.*)": ["<rootDir>/lib/types/$1"],
        "^@types": ["<rootDir>/lib/types/index"],
        "^@validators/(.*)": ["<rootDir>/lib/validators/$1gh"],
        "^@validators": ["<rootDir>/lib/validators/index"],
        "^~specs/(.*)": ["<rootDir>/specs/$1"],
        "^~specs": ["<rootDir>/specs/index"],
        "^~configs": ["<rootDir>/specs/configs/index"],
        "^~errors": ["<rootDir>/specs/errors/index"],
        "^~fails": ["<rootDir>/specs/fails/index"],
        "^~helpers": ["<rootDir>/specs/helpers/index"],
        "^~mocks": ["<rootDir>/specs/mocks/index"],
        "^~lifecycles": ["<rootDir>/specs/lifecycles/index"],
    },
    notify: true,
    moduleFileExtensions: ["js", "json", "ts", "template"],
    rootDir: ".",
    testRegex: ".*\\.spec\\.ts$",
    transform: {
        "^.+\\.(t|j)s$": "ts-jest",
    },
    collectCoverageFrom: ["**/*.(t)s"],
    coverageDirectory: "./coverage",
    coveragePathIgnorePatterns: ["dist", "dist:check", "dist:specs", "coverage", "specs", "node_modules"],
    setupFilesAfterEnv: ["<rootDir>/specs/specs.setup.ts"],
};
